baseURL = "https://hidevops.io/"
languageCode = "en-us"
title = "hidevops.io | Continuous Integration and Continuous Delivery"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    # [[menu.nav]]
    #     name    = "About"
    #     url     = "/about"
    #     weight  = 2
    [[menu.nav]]
        name    = "Hiboot"
        url     = "https://hiboot.hidevops.io"
        weight  = 3
    # [[menu.nav]]
    #     name    = "Gallery"
    #     url     = "/gallery"
    #     weight  = 4
    # [[menu.nav]]
    #     name    = "Blog"
    #     url     = "/blog"
    #     weight  = 5
    # [[menu.nav]]
    #     name    = "Contact"
    #     url     = "/contact"
    #     weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    logo = "images/hidevops.png"
    logo_alt = "logo"
    #logo_text = "logo_text"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/cloud.jpg"
        heading = "HI, MY NAME IS JOHN DENG & I AM A"
        description = "WITH 20 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING JAVA EXPERT, GOPHER, CLOUD NATIVE EVANGELIST, DOMAIN DRIVEN DESIGN EXPERT, AND SOFTWARE ARCHITECT"
        btn     = true
        btnText = "Hiboot"
        btnURL  = "https://hiboot.hidevops.io/"
        [[params.banner.flipText]]
            title   = "JAVA EXPERT"
        [[params.banner.flipText]]
            title   = "GOPHER"    
        [[params.banner.flipText]]
            title   = "EVANGELIST"
        [[params.banner.flipText]]
            title   = "DOMAIN EXPERT"
        [[params.banner.flipText]]
            title   = "ARCHITECT"

    # Homepage About Section
    # [params.about]
    #     enable  = true
    #     title   = "ABOUT ME"
    #     content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
    #     image   = "images/about/about.jpg"

    # Call to Action
    # [params.cta]
    #     enable  = true
    #     title   = "SO WHAT YOU THINK ?"
    #     content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
    #     btnText = "Contact with me"
    #     btnURL  = "/contact"

    # # Portfolio Section On Homepage
    # [params.portfolio]
    #     enable  = true
    #     title   = "Latest Works"
    #     subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # # Feature Product Section
    # [params.featureProduct]
    #     enable  = true
    #     title   = "SOME OF OUR FEATURES WORKS"
    #     subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        customized  = true # Set this variable to true if you customized the design.
        copyright_owner = "John Deng"
        copyright_since = "2018"
        # [[params.footer.social]]
        #     icon = "ion-social-facebook"
        #     link = "https://facebook.com"
        [[params.footer.social]]
            icon = "ion-social-twitter"
            link = "https://twitter.com/johndcn"
        # [[params.footer.social]]
        #     icon = "ion-social-linkedin"
        #     link = "https://linkedin.com"
        # [[params.footer.social]]
        #     icon = "ion-social-googleplus"
        #     link = "https://googleplus.com"
        [[params.footer.social]]
            icon = "ion-social-github"
            link = "https://github.com/hidevopsio"
    